[package]
name = "legacy-relay"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.5" }
mongodb = { version = "2.3" }
tokio = { version = "1", features = ["full"] }
